# Generated by Django 4.1.1 on 2022-10-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookshelf',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=288)),
                ('book_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('book_doc', models.FileField(upload_to='scripts')),
            ],
        ),
        migrations.DeleteModel(
            name='library',
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('bookshelf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='locker.bookshelf')),
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=500)),
                ('course_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_context', models.FileField(upload_to='scripts')),
            ],
            bases=('locker.bookshelf',),
        ),
    ]
