# Generated by Django 4.1.1 on 2022-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_bookshelf_delete_library_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('task_status', models.BooleanField()),
            ],
        ),
    ]
