# Generated by Django 4.1.1 on 2023-02-16 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0004_todo_due_date_alter_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 12, 16, 54, 500791)),
        ),
    ]
