option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: bytai/wsgi.py
  aws:elasticbeanstalk:container:python:staticfiles:
    /static/: static/
  aws:elasticbeanstalk:container:python:staticfiles:
    /media/: media/
  aws:elasticbeanstalk:application:environment:
    DJANGO_SETTINGS_MODULE: bytai.settings
    PYTHONPATH: /opt/python/current/app/bytai:$PYTHONPATH
    SECRET_KEY: 7/?OVwkBhqYPvcFLJ$>fBI"SNu>^hUQA.B`s[JL6Hs^";RA)"8
#  selfbyt.us-east-1.elasticbeanstalk.com