# Generated by Django 4.1.1 on 2022-09-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=70)),
                ('First_name', models.CharField(max_length=70)),
                ('Last_name', models.CharField(max_length=70)),
                ('profile_image', models.ImageField(default=None, upload_to='media')),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('telephone', models.IntegerField()),
            ],
        ),
    ]
