# Generated by Django 4.1.7 on 2023-03-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfbyt_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='blog', max_length=1000),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AddField(
            model_name='opensource',
            name='link',
            field=models.CharField(default='link', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='research',
        ),
    ]
